version: '3.7'
services:
  gitlab-ce:
    image: 'gitlab/gitlab-ce:latest'
    restart: 'always'
    hostname: 'localhost'
    container_name: 'gitlab-ce'
    environment:
      GITLAB_OMNIBUS_CONFIG:
        external_url 'http://localhost:10080'
        gitlab_rails['initial_root_password'] 'root'
    ports:
      - '10080:10080'
      - '10443:10443'
    networks:
      - gitlab
  gitlab-runner:
    image: 'gitlab/gitlab-runner:alpine'
    restart: 'always'
    container_name: 'gitlab-runner'
    depends_on:
      - web
    networks:
      - gitlab
  sonarqube_db:
    image: 'postgres:latest'
    restart: 'unless-stopped'
    container_name: 'sonarqube_db'
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
  sonarqube:
    image: 'sonarqube:latest'
    restart: 'unless-stopped'
    container_name: 'sonarqube'
    environment:
      SONARQUBE_JDBC_USERNAME:
      SONARQUBE_JDBC_PASSWORD:
      SONARQUBE_JDBC_URL:
    ports:
      - '19000:9000'
      - '19092:9092'
networks:
  gitlab:
    name: 'gitlab-network'
