version: '3.7'
services:
  gitlab-ce:
    image: 'gitlab/gitlab-ce:latest'
    restart: 'always'
    hostname: 'localhost'
    container_name: 'gitlab-ce'
    ports:
      - '1080:1080'
      - '1443:1443'
      - '1022:22'
    volumes:
      - ./dirs\gitlab-ce/config:/etc/gitlab
      - ./dirs\gitlab-ce/data:/var/opt/gitlab
      - ./dirs\gitlab-ce/logs:/var/log/gitlab
    networks:
      - devops
  gitlab-runner:
    image: 'gitlab/gitlab-runner:alpine'
    restart: 'always'
    hostname: 'gitlab-runner'
    container_name: 'gitlab-runner'
    depends_on:
      - gitlab-ce
    volumes:
      - ./dirs\gitlab-runner:/etc/gitlab-runner
    networks:
      - devops
  postgres_db:
    image: 'postgres:latest'
    restart: 'always'
    hostname: 'postgres_db'
    container_name: 'postgres_db'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_MULTIPLE_DATABASES=sonarqube:admin,allure:admin
    volumes:
      - ./dirs\postgresql:/var/lib/postgresql
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - devops
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    restart: 'always'
    container_name: 'pgadmin'
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '2080:80'
    networks:
      - devops
  sonarqube:
    image: 'sonarqube:latest'
    restart: 'always'
    hostname: 'sonarqube'
    container_name: 'sonarqube'
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=admin
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres_db:5432/sonarqube
    ports:
      - '9000:9000'
    depends_on:
      - postgres_db
    volumes:
      - ./dirs\sonarqube/data:/opt/sonarqube/data
      - ./dirs\sonarqube/extensions:/opt/sonarqube/extensions
      - ./dirs\sonarqube/logs:/opt/sonarqube/logs
    networks:
      - devops
networks:
  devops:
    name: 'devops-network'
