version: '3.7'
services:
  gitlab-ce:
    image: 'gitlab/gitlab-ce:latest'
    restart: 'always'
    hostname: 'localhost'
    container_name: 'gitlab-ce'
    ports:
      - '1080:1080'
      - '1443:1443'
      - '1022:22'
    volumes:
      - ./config:/etc/gitlab
    networks:
      - devops
  gitlab-runner:
    image: 'gitlab/gitlab-runner:alpine'
    restart: 'always'
    hostname: 'gitlab-runner'
    container_name: 'gitlab-runner'
    depends_on:
      - gitlab-ce
    networks:
      - devops
  postgres_db:
    image: 'postgres:latest'
    restart: 'unless-stopped'
    hostname: 'postgres_db'
    container_name: 'postgres_db'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_MULTIPLE_DATABASES=sonarqube:admin,allure:admin
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    networks:
      - devops
  sonarqube:
    image: 'sonarqube:latest'
    restart: 'unless-stopped'
    hostname: 'sonarqube'
    container_name: 'sonarqube'
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=admin
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres_db:5432/sonarqube
    ports:
      - '19000:9000'
      - '19092:9092'
    networks:
      - devops
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1500M'
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    restart: 'always'
    container_name: 'pgadmin'
    environment:
      - PGADMIN_DEFAULT_EMAIL=raj@nola.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '2080:80'
    networks:
      - devops
networks:
  devops:
    name: 'devops-network'
